### ISSUE TITLE
Udacity Project Review

### ISSUE THREAD

**Issue by madhur-taneja** [mina20088/landing-page#1]
Hi @mina20088,

I'm the reviewer who reviewed your project and I'm glad you left your Github link in the comments. To justify my review and clarify your doubts that you mentioned in your comments,

![Capture](https://user-images.githubusercontent.com/24964149/90793120-f6fa0980-e328-11ea-87c3-d7aeeab67ca2.PNG)

here's an explanation:

Yes, of course, the highlights are being added but as I also mentioned in the review, they should be dynamic i.e. change as the user scrolls through the page and not just on clicking. Here's a working example of what is expected of you for this project:

https://madhur-taneja.github.io/Landing-Page/

I also provided the following explanation to make it more clear, but only if you would have read the review properly. 

> To understand why we need active classes for the nav links, let suppose the sections are very large. In that case, one has to scroll to the top of that section to know which section is being viewed currently. This is not good for the user's experience. Refer to this article for help.

In the future, please be careful with what rating you provide to the reviewers as it's an important aspect for both us and Udacity. Read the reviews properly, if you struggle to understand the language then reach out to mentors on `Knowledge Platform` to confirm, and if they point out that its wrong then feel free to rate even 1 star if you'd like. Hope this helps.

Good luck & Happy Learning!

**Comment by mina20088** [comment]
hello participant i will consider this as a direct insult to me and i will send the mentor of udacity because i know how to speak English and i understand English

**Comment by madhur-taneja** [comment]
Hello Student,

By "struggle to understand the language", I meant if you're not able to understand the context of the feedback or somehow are unsure of what is being conveyed; not that you don't know or understand English as a language as sometimes it's purely technical and requires more than just understanding English. Hope this clears the misunderstanding you had.

**Comment by mina20088** [comment]
hi as a reviewer can i add more than on js file to the project or i should only have the app.js

**Comment by madhur-taneja** [comment]
You are free to add more `js` files in your project if you want to if you feel the code needs to be more modular.

**Comment by mina20088** [comment]
Ok thank you by the way I passed the project

**Comment by madhur-taneja** [comment]
Great! Congrats
